namespace Buggary.BuggaryEditor.Infrastructure
{
    public static class Defaults
    {
        public static string[] DefaultCodeList;
        public static string[] CurrentTest;
        public static string[] LongBoy;

        static Defaults()
        {
            CurrentTest = new string[]
            {
                "using UnityEngine;",
                "// default code",
                "public class One : MonoBehaviour",
                "{",
                "    GameObject go;",
                "    private void Start()",
                "    {",
                "        go = GameObject.Find(\"Capsule\");",
                "    }",
                "    public void Update()",
                "    {",
                "        go",
                "    }",
                "}",
                "",
            };

            DefaultCodeList = new string[]
            {
                "using UnityEngine;",
                "",
                "public class One : MonoBehaviour",
                "{",
                "    private void Start()",
                "    {",
                "        this.",
                "    }",
                "    public MonoBehaviour ToMono()",
                "    {",
                "        return this;",
                "    }",
                "}",
                "",
            };

            LongBoy = new string []
            {
                "using UnityEngine;",
                "",
                "public class One : MonoBehaviour",
                "{",
                "    private void Start()",
                "    {",
                "        this.",
                "    }",
                "    public MonoBehaviour ToMono()",
                "    {",
                "        return this;",
                "    }",
                "}",
                "",
                "public class Two : MonoBehaviour",
                "{",
                "    private void Start()",
                "    {",
                "        this.",
                "    }",
                "    public MonoBehaviour ToMono()",
                "    {",
                "        return this;",
                "    }",
                "}",
                "",
                "public class Three : MonoBehaviour",
                "{",
                "    private void Start()",
                "    {",
                "        this.",
                "    }",
                "    public MonoBehaviour ToMono()",
                "    {",
                "        return this;",
                "    }",
                "}",
                "",
                "public class Four : MonoBehaviour",
                "{",
                "    private void Start()",
                "    {",
                "        this.",
                "    }",
                "    public MonoBehaviour ToMono()",
                "    {",
                "        return this;",
                "    }",
                "}",
                "",
                "public class Five : MonoBehaviour",
                "{",
                "    private void Start()",
                "    {",
                "        this.",
                "    }",
                "    public MonoBehaviour ToMono()",
                "    {",
                "        return this;",
                "    }",
                "}",
                "",
                "public class Six : MonoBehaviour",
                "{",
                "    private void Start()",
                "    {",
                "        this.",
                "    }",
                "    public MonoBehaviour ToMono()",
                "    {",
                "        return this;",
                "    }",
                "}",
                "",
                "public class Seven : MonoBehaviour",
                "{",
                "    private void Start()",
                "    {",
                "        this.",
                "    }",
                "    public MonoBehaviour ToMono()",
                "    {",
                "        return this;",
                "    }",
                "}",
                "",
                "public class Eight : MonoBehaviour",
                "{",
                "    private void Start()",
                "    {",
                "        this.",
                "    }",
                "    public MonoBehaviour ToMono()",
                "    {",
                "        return this;",
                "    }",
                "}",
                "",
                "public class Nine : MonoBehaviour",
                "{",
                "    private void Start()",
                "    {",
                "        this.",
                "    }",
                "    public MonoBehaviour ToMono()",
                "    {",
                "        return this;",
                "    }",
                "}",
                "",
            };
        }
    }
}